apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ningxone
  name: ningxone
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ningxone
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ningxone
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
